updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: gradle
    directory: "/example/android"
    schedule:
      interval: daily
    reviewers:
      - "juliansteenbakker"